### ISSUE TITLE
Site Usability Feedback

### ISSUE THREAD

**Issue by PeterNorton** [PeterNorton/QTLNetMiner#10]
Site feedback from Ross, Ajit and Keywan:
- ~~Colour of gene markers is broken, has been fixed in the Issue #9 branch.~~
- ~~Infobox had to be disabled because of incompatible JQuery versions.~~
- ~~Infobox doesn't move as you pan~~
- ~~Pan region too wide when zoomed out~~
- ~~Increase Gene marker size to make them easier to click on, introduce hover effect~~
- ~~Close the Infobox on mouseup and zoom~~
- ~~Disable multiple Infoboxes being visible at one time~~
- ~~Reduce the width of the QTL region bars~~
- ~~Test the component with the rest of the site .css~~
- ~~Combine the Infobox content, remove the heading and add the link to the Gene name.~~

**Comment by AjitPS** [comment]
A useful (key) feature to have:
- A high-priority feature to have is allowing multi-select for genes with a button within the Map View container to "Show Network" for all of them (i.e., launch the KNETViewer for all of them). Users should also be able to individually see the network for a gene via the Infobox.

Some notes:
- Regarding the creation of the initial Map, it presently causes an exception if the annotation file is not provided (null), I'll look into avoiding that.
- I'll also work on limiting the scope of jQuery for bootstrap to the Map View container to prevent conflicts and avoid breaking other existing features like the Query suggester, example queries, etc.

**Comment by PeterNorton** [comment]
I've added the multi-select issue as Issue #12. I can't reproduce the problem when null is provided as the second argument. I'm trying to re-create the embedded scenario and test it there. There isn't much error handling in the XML parsing so it may be something to do with that.
