### ISSUE TITLE
Zoom & Pan

### ISSUE THREAD

**Issue by PeterNorton** [PeterNorton/QTLNetMiner#3]

**Comment by PeterNorton** [comment]
There are a number of ways to improve the pan + zoom functionality, thinks like:
- Adding scroll bars
- Adding an flexible edge that lets you 'pull' it a bit before bouncing back. Like the behavior common on mobiles.
- Adding a thumbnail when you zoom in.

**Comment by AjitPS** [comment]
Interesting, the thumbnail would be a nice enhancement to look into, once the basic version of Map View is complete.
