### ISSUE TITLE
Adjustable Chromosome Layout

### ISSUE THREAD

**Issue by PeterNorton** [PeterNorton/QTLNetMiner#4]
Can adjust the number of chromosomes displayed in each row.

**Comment by AjitPS** [comment]
@PeterNorton : looks good, would be good to have all the chromosomes initially visible in the viewport (as discussed earlier today).
The users should see all the chromosomes as first and can later zoom to a particular row and a particular chromosome or region within a chromosome.

**Comment by PeterNorton** [comment]
I've added a new automatic layout that should ensure all the chromosomes are initially visible. The Chromosomes look a little squashed when there are lots of rows. Maybe adding a minimum aspect ratio would help with this.
